-- Postgres keyword and built-in reference, keyed by uppercase name.
-- SQL has nowhere to put a doc-comment, so no language server can hover a bare
-- `LATERAL` or `COALESCE`; this table is what stands in for that documentation.
-- `sig` is the shape of the construct, `doc` what it does, and `rust` on a type is
-- what sqlx decodes it into. Multi-word entries are matched greedily by the caller,
-- so `ON CONFLICT` wins over a bare `ON`.

local K = 'keyword'
local F = 'function'
local O = 'operator'
local T = 'type'

return {
  -- query ---------------------------------------------------------------------
  ['SELECT'] = { kind = K, sig = 'SELECT [DISTINCT [ON (expr)]] target [, ...] [FROM from_item]',
    doc = 'Reads rows. Output columns are computed after FROM/WHERE/GROUP BY, so an alias defined in the target list cannot be used in WHERE - only in ORDER BY and GROUP BY.' },
  ['DISTINCT'] = { kind = K, sig = 'SELECT DISTINCT target [, ...]',
    doc = 'Drops duplicate result rows, comparing every output column. NULLs count as equal here, unlike in a `=` comparison.' },
  ['DISTINCT ON'] = { kind = K, sig = 'SELECT DISTINCT ON (expr [, ...]) target ... ORDER BY expr [, ...]',
    doc = 'Postgres extension: keeps the first row of each group of equal `expr`. Which row is first is decided by ORDER BY, which must start with the same expressions - without that the kept row is arbitrary.' },
  ['FROM'] = { kind = K, sig = 'FROM table [[AS] alias] [, ...] | (subquery) alias | func() | LATERAL ...',
    doc = 'Names the row sources. Comma between items is a CROSS JOIN.' },
  ['WHERE'] = { kind = K, sig = 'WHERE condition',
    doc = 'Filters rows before grouping. A row passes only when the condition is true - both false and NULL drop it.' },
  ['AS'] = { kind = K, sig = 'expr AS name | table AS alias | CAST(x AS type)',
    doc = 'Names a result column, a table alias, or the target type of a cast.' },
  ['ONLY'] = { kind = K, sig = 'FROM ONLY table',
    doc = 'Excludes rows of inheriting child tables, which are otherwise scanned along with the parent.' },

  -- joins ---------------------------------------------------------------------
  ['JOIN'] = { kind = K, sig = 'a [INNER | LEFT | RIGHT | FULL] JOIN b ON cond | USING (col)',
    doc = 'Combines two row sources. Bare JOIN means INNER: only pairs matching the condition survive.' },
  ['INNER JOIN'] = { kind = K, sig = 'a INNER JOIN b ON cond',
    doc = 'Keeps only rows with a match on both sides.' },
  ['LEFT JOIN'] = { kind = K, sig = 'a LEFT [OUTER] JOIN b ON cond',
    doc = 'Keeps every left row; unmatched right columns come back NULL. Moving a condition on `b` from ON to WHERE turns this back into an inner join, because NULL fails the test.' },
  ['RIGHT JOIN'] = { kind = K, sig = 'a RIGHT [OUTER] JOIN b ON cond',
    doc = 'Keeps every right row; unmatched left columns come back NULL.' },
  ['FULL JOIN'] = { kind = K, sig = 'a FULL [OUTER] JOIN b ON cond',
    doc = 'Keeps unmatched rows from both sides, padding the other with NULL.' },
  ['CROSS JOIN'] = { kind = K, sig = 'a CROSS JOIN b',
    doc = 'Cartesian product - every left row paired with every right row. No ON clause.' },
  ['LATERAL'] = { kind = K, sig = 'FROM a, LATERAL (SELECT ... WHERE x = a.id) b',
    doc = 'Lets a FROM item reference columns of items to its left, so the subquery is re-evaluated per outer row. This is how you write a per-row top-N. With LEFT JOIN LATERAL ... ON true the outer row survives even when the subquery returns nothing.' },
  ['ON'] = { kind = K, sig = 'JOIN b ON condition',
    doc = 'Join condition. Any boolean expression, not only equality.' },
  ['USING'] = { kind = K, sig = 'JOIN b USING (col [, ...]) | DELETE ... USING table',
    doc = 'Join shorthand when both sides name the column identically: it is compared and then collapsed into one output column. In DELETE it names extra tables to read.' },

  -- grouping and ordering -----------------------------------------------------
  ['GROUP BY'] = { kind = K, sig = 'GROUP BY expr [, ...] | GROUPING SETS | ROLLUP | CUBE',
    doc = 'Collapses rows into one per distinct key. Every target-list column must then be either a grouping key or wrapped in an aggregate.' },
  ['HAVING'] = { kind = K, sig = 'HAVING condition',
    doc = 'Filters groups after aggregation, so it can test aggregates - which WHERE cannot, because WHERE runs first.' },
  ['ORDER BY'] = { kind = K, sig = 'ORDER BY expr [ASC | DESC] [NULLS FIRST | NULLS LAST] [, ...]',
    doc = 'Sorts the result. Without it row order is undefined, even if it looks stable. Default is ASC with NULLS LAST (DESC defaults to NULLS FIRST).' },
  ['ASC'] = { kind = K, sig = 'ORDER BY expr ASC', doc = 'Ascending, the default. NULLs sort last.' },
  ['DESC'] = { kind = K, sig = 'ORDER BY expr DESC', doc = 'Descending. NULLs sort first unless you say NULLS LAST.' },
  ['NULLS FIRST'] = { kind = K, sig = 'ORDER BY expr DESC NULLS FIRST', doc = 'Places NULLs before non-NULL values.' },
  ['NULLS LAST'] = { kind = K, sig = 'ORDER BY expr DESC NULLS LAST', doc = 'Places NULLs after non-NULL values.' },
  ['LIMIT'] = { kind = K, sig = 'LIMIT count | ALL',
    doc = 'Caps returned rows. Meaningless without ORDER BY, since which rows you get is then arbitrary.' },
  ['OFFSET'] = { kind = K, sig = 'OFFSET start',
    doc = 'Skips rows before returning. The skipped rows are still computed, so deep offsets get slower the further you page; keyset pagination (WHERE id > last) does not.' },
  ['FETCH'] = { kind = K, sig = 'FETCH FIRST n ROWS ONLY | WITH TIES',
    doc = 'Standard spelling of LIMIT. WITH TIES also returns rows tying with the last one under ORDER BY.' },

  -- set operations and CTEs ---------------------------------------------------
  ['WITH'] = { kind = K, sig = 'WITH name AS [NOT] MATERIALIZED (query) [, ...] SELECT ...',
    doc = 'Common table expression: a named subquery for this statement. Since PG12 a plain CTE used once is folded into the outer query; MATERIALIZED forces it to run separately, NOT MATERIALIZED forces inlining.' },
  ['RECURSIVE'] = { kind = K, sig = 'WITH RECURSIVE name AS (base UNION [ALL] recursive_term)',
    doc = 'Lets a CTE reference itself, for trees and graphs. The recursive term runs repeatedly on the previous round until it returns no rows - UNION dedupes and so terminates on cycles, UNION ALL does not.' },
  ['UNION'] = { kind = K, sig = 'query UNION query',
    doc = 'Concatenates two results and removes duplicates - which costs a sort or hash. Use UNION ALL when you know there are none.' },
  ['UNION ALL'] = { kind = K, sig = 'query UNION ALL query',
    doc = 'Concatenates without deduplicating. Cheaper than UNION.' },
  ['INTERSECT'] = { kind = K, sig = 'query INTERSECT [ALL] query', doc = 'Rows present in both results.' },
  ['EXCEPT'] = { kind = K, sig = 'query EXCEPT [ALL] query', doc = 'Rows of the first result that are absent from the second.' },
  ['VALUES'] = { kind = K, sig = 'VALUES (expr, ...) [, ...]',
    doc = 'A literal row set. Usable anywhere a table is, so `(VALUES (1),(2)) AS t(n)` is a quick inline table.' },

  -- predicates ----------------------------------------------------------------
  ['EXISTS'] = { kind = K, sig = 'EXISTS (subquery)',
    doc = 'True when the subquery returns at least one row. Stops at the first, so `SELECT 1` inside is idiomatic; unlike IN it is unaffected by NULLs.' },
  ['IN'] = { kind = K, sig = 'expr IN (value, ...) | expr IN (subquery)',
    doc = 'Membership test. Careful with NOT IN over a set containing NULL: the result is NULL, never true, so the row silently disappears.' },
  ['ANY'] = { kind = K, sig = 'expr op ANY (array | subquery)',
    doc = 'True when the comparison holds for at least one element. `= ANY($1)` is how sqlx passes a Rust Vec as an IN list.' },
  ['ALL'] = { kind = K, sig = 'expr op ALL (array | subquery)',
    doc = 'True when the comparison holds for every element, and trivially true for an empty set.' },
  ['BETWEEN'] = { kind = K, sig = 'expr BETWEEN low AND high',
    doc = 'Inclusive on both ends. For timestamps that makes an upper bound of midnight include exactly that instant, so half-open `>= a AND < b` is usually what you want.' },
  ['LIKE'] = { kind = K, sig = "string LIKE pattern [ESCAPE char]",
    doc = "Pattern match with `%` (any run) and `_` (one character). Anchored at both ends, so a bare pattern must describe the whole string." },
  ['ILIKE'] = { kind = K, sig = 'string ILIKE pattern',
    doc = 'Case-insensitive LIKE - a Postgres extension. Cannot use a plain btree index; a text_pattern_ops or trigram index can serve it.' },
  ['SIMILAR TO'] = { kind = K, sig = 'string SIMILAR TO pattern',
    doc = 'SQL-standard pattern match, a regex/LIKE hybrid. Rarely worth it - `~` is the real regex operator.' },
  ['IS NULL'] = { kind = K, sig = 'expr IS NULL',
    doc = 'The only correct NULL test: `= NULL` yields NULL, which is not true, so it never matches.' },
  ['IS NOT NULL'] = { kind = K, sig = 'expr IS NOT NULL', doc = 'True when the value is not NULL.' },
  ['IS DISTINCT FROM'] = { kind = K, sig = 'a IS DISTINCT FROM b',
    doc = 'Inequality that treats NULL as a value: NULL IS DISTINCT FROM 1 is true, and two NULLs are not distinct. This is what trigger bodies use to detect a real change.' },
  ['IS NOT DISTINCT FROM'] = { kind = K, sig = 'a IS NOT DISTINCT FROM b',
    doc = 'Equality treating two NULLs as equal.' },
  ['CASE'] = { kind = K, sig = 'CASE WHEN cond THEN result [...] [ELSE result] END',
    doc = 'Conditional expression. Arms are evaluated in order and the rest are skipped; without ELSE an unmatched row yields NULL.' },
  ['FILTER'] = { kind = K, sig = 'agg(expr) FILTER (WHERE cond)',
    doc = 'Restricts one aggregate to matching rows, so several differently-filtered counts can share a single scan. Cleaner than the CASE-inside-SUM trick.' },
  ['CAST'] = { kind = K, sig = 'CAST(expr AS type) | expr::type',
    doc = 'Type conversion. `::` is the Postgres shorthand and binds tighter than most operators, so parenthesise when in doubt.' },

  -- window functions ----------------------------------------------------------
  ['OVER'] = { kind = K, sig = 'func() OVER ([PARTITION BY ...] [ORDER BY ...] [frame])',
    doc = 'Turns a call into a window function: it sees a set of rows but does not collapse them, so each input row keeps its own output row.' },
  ['PARTITION BY'] = { kind = K, sig = 'OVER (PARTITION BY expr [, ...])',
    doc = 'Splits rows into independent windows; the function restarts for each. Like GROUP BY, but without folding rows away.' },
  ['WINDOW'] = { kind = K, sig = 'WINDOW name AS (definition)',
    doc = 'Names a window definition so several calls can share it.' },
  ['ROW_NUMBER'] = { kind = F, sig = 'row_number() OVER (...) -> bigint',
    doc = 'Sequential position within the window, starting at 1. Ties get different numbers, arbitrarily - use rank() if that matters.' },
  ['RANK'] = { kind = F, sig = 'rank() OVER (...) -> bigint',
    doc = 'Position with gaps: tied rows share a rank and the next value skips ahead.' },
  ['DENSE_RANK'] = { kind = F, sig = 'dense_rank() OVER (...) -> bigint',
    doc = 'Position without gaps: tied rows share a rank and the next value is one higher.' },
  ['NTILE'] = { kind = F, sig = 'ntile(buckets int) OVER (...) -> int',
    doc = 'Splits the window into that many roughly equal buckets and returns the bucket number.' },
  ['LAG'] = { kind = F, sig = 'lag(value [, offset [, default]]) OVER (...)',
    doc = 'Value from a preceding row of the window; NULL (or `default`) before the start.' },
  ['LEAD'] = { kind = F, sig = 'lead(value [, offset [, default]]) OVER (...)',
    doc = 'Value from a following row of the window.' },
  ['FIRST_VALUE'] = { kind = F, sig = 'first_value(value) OVER (...)', doc = 'Value from the first row of the frame.' },
  ['LAST_VALUE'] = { kind = F, sig = 'last_value(value) OVER (...)',
    doc = 'Value from the last row of the frame - which by default ends at the current row, so this often needs an explicit ROWS BETWEEN ... AND UNBOUNDED FOLLOWING.' },

  -- insert / update / delete --------------------------------------------------
  ['INSERT'] = { kind = K, sig = 'INSERT INTO table [(cols)] { VALUES ... | query } [ON CONFLICT ...] [RETURNING ...]',
    doc = 'Adds rows. Naming the columns explicitly keeps the statement working when the table gains one.' },
  ['ON CONFLICT'] = { kind = K, sig = 'ON CONFLICT [(cols) | ON CONSTRAINT name] DO { NOTHING | UPDATE SET ... }',
    doc = 'Upsert. The conflict target infers a unique index; DO UPDATE needs one, DO NOTHING does not. The row that failed to insert is visible as `EXCLUDED`.' },
  ['DO NOTHING'] = { kind = K, sig = 'ON CONFLICT DO NOTHING',
    doc = 'Skips conflicting rows silently. They are not returned by RETURNING either, so a caller cannot tell insert from skip without a follow-up read.' },
  ['DO UPDATE'] = { kind = K, sig = 'ON CONFLICT (cols) DO UPDATE SET c = EXCLUDED.c [WHERE cond]',
    doc = 'Turns the conflict into an update of the existing row. Takes a row lock, so concurrent upserts of the same key serialise.' },
  ['EXCLUDED'] = { kind = K, sig = 'EXCLUDED.column',
    doc = 'Inside DO UPDATE, the row that was proposed for insertion, as opposed to the stored one addressed by table name.' },
  ['RETURNING'] = { kind = K, sig = 'INSERT/UPDATE/DELETE ... RETURNING expr [, ...]',
    doc = 'Returns the affected rows from a write, so a generated id or a computed default comes back without a second round trip. This is what `query_as!` reads after an INSERT.' },
  ['UPDATE'] = { kind = K, sig = 'UPDATE table SET col = expr [, ...] [FROM ...] [WHERE cond] [RETURNING ...]',
    doc = 'Modifies rows. Without WHERE it rewrites the whole table. FROM lets you pull values from another table.' },
  ['SET'] = { kind = K, sig = 'SET col = expr | SET (a, b) = (SELECT ...)',
    doc = 'Assignment list of an UPDATE. All right-hand sides see the pre-update row, so the order of assignments does not matter.' },
  ['DELETE'] = { kind = K, sig = 'DELETE FROM table [USING ...] [WHERE cond] [RETURNING ...]',
    doc = 'Removes rows and leaves dead tuples for VACUUM. Without WHERE it empties the table row by row - TRUNCATE is far faster for that.' },
  ['TRUNCATE'] = { kind = K, sig = 'TRUNCATE [TABLE] name [, ...] [RESTART IDENTITY] [CASCADE]',
    doc = 'Empties tables by dropping their storage. Transactional in Postgres, but takes an ACCESS EXCLUSIVE lock and fires no row triggers.' },
  ['MERGE'] = { kind = K, sig = 'MERGE INTO target USING source ON cond WHEN MATCHED THEN ... WHEN NOT MATCHED THEN ...',
    doc = 'Conditional insert/update/delete against a source relation (PG15+). Unlike ON CONFLICT it needs no unique index, but it is not proof against concurrent inserts.' },

  -- locking -------------------------------------------------------------------
  ['FOR UPDATE'] = { kind = K, sig = 'SELECT ... FOR UPDATE [OF table] [NOWAIT | SKIP LOCKED]',
    doc = 'Row-locks the selected rows for the rest of the transaction, blocking other writers and lockers. The classic read-modify-write guard.' },
  ['FOR NO KEY UPDATE'] = { kind = K, sig = 'SELECT ... FOR NO KEY UPDATE',
    doc = 'Weaker FOR UPDATE that still allows concurrent foreign-key references to the row.' },
  ['FOR SHARE'] = { kind = K, sig = 'SELECT ... FOR SHARE',
    doc = 'Shared row lock: concurrent readers with FOR SHARE pass, writers block.' },
  ['SKIP LOCKED'] = { kind = K, sig = 'SELECT ... FOR UPDATE SKIP LOCKED',
    doc = 'Silently omits rows already locked by someone else instead of waiting. This is what makes a table usable as a work queue for competing consumers.' },
  ['NOWAIT'] = { kind = K, sig = 'SELECT ... FOR UPDATE NOWAIT',
    doc = 'Raises an error at once rather than waiting for a conflicting row lock.' },

  -- transactions --------------------------------------------------------------
  ['COMMIT'] = { kind = K, sig = 'COMMIT', doc = 'Ends the transaction and makes its changes durable and visible.' },
  ['ROLLBACK'] = { kind = K, sig = 'ROLLBACK [TO SAVEPOINT name]', doc = 'Discards the transaction, or unwinds it to a savepoint.' },
  ['SAVEPOINT'] = { kind = K, sig = 'SAVEPOINT name',
    doc = 'A named point to roll back to without losing the whole transaction. sqlx opens one for each nested `begin()`.' },
  ['ISOLATION LEVEL'] = { kind = K, sig = 'SET TRANSACTION ISOLATION LEVEL { READ COMMITTED | REPEATABLE READ | SERIALIZABLE }',
    doc = 'Postgres defaults to READ COMMITTED, where each statement sees a fresh snapshot. The stricter levels can abort with a serialization failure, so callers must be ready to retry.' },

  -- ddl -----------------------------------------------------------------------
  ['PRIMARY KEY'] = { kind = K, sig = 'col type PRIMARY KEY | PRIMARY KEY (col, ...)',
    doc = 'Unique plus NOT NULL, and the default target of foreign keys. Creates a unique index.' },
  ['FOREIGN KEY'] = { kind = K, sig = 'FOREIGN KEY (col) REFERENCES other(col) [ON DELETE ...] [ON UPDATE ...]',
    doc = 'Constrains values to exist in another table. Postgres does not index the referencing column for you - and without that index, deletes on the parent scan the child.' },
  ['REFERENCES'] = { kind = K, sig = 'col type REFERENCES other(col)', doc = 'Column-level foreign key.' },
  ['ON DELETE'] = { kind = K, sig = 'ON DELETE { NO ACTION | RESTRICT | CASCADE | SET NULL | SET DEFAULT }',
    doc = 'What happens to referencing rows when the referenced row goes. Default NO ACTION rejects the delete, checked at end of statement; RESTRICT rejects it immediately.' },
  ['CASCADE'] = { kind = K, sig = 'ON DELETE CASCADE | DROP ... CASCADE',
    doc = 'Propagates the operation to dependent rows or objects. On DROP it silently removes whatever depends on the object.' },
  ['CHECK'] = { kind = K, sig = 'CHECK (condition)',
    doc = 'Row-level invariant enforced on write. A NULL result passes - the constraint only rejects an outright false.' },
  ['UNIQUE'] = { kind = K, sig = 'UNIQUE (col, ...) [NULLS NOT DISTINCT]',
    doc = 'Rejects duplicate values via a unique index. NULLs are distinct by default, so several NULLs coexist; PG15+ can change that with NULLS NOT DISTINCT.' },
  ['NOT NULL'] = { kind = K, sig = 'col type NOT NULL', doc = 'Rejects NULL. sqlx reads this to decide whether the Rust field is `T` or `Option<T>`.' },
  ['DEFAULT'] = { kind = K, sig = 'col type DEFAULT expr',
    doc = 'Value used when the column is omitted from an INSERT. Evaluated per row at insert time, so `now()` is the row timestamp, not the migration time.' },
  ['GENERATED'] = { kind = K, sig = 'col type GENERATED ALWAYS AS (expr) STORED | GENERATED ... AS IDENTITY',
    doc = 'A computed column stored on write, or a standard-SQL identity sequence. Identity is the modern replacement for `serial`.' },
  ['CREATE INDEX'] = { kind = K, sig = 'CREATE [UNIQUE] INDEX [CONCURRENTLY] name ON table [USING method] (cols) [WHERE cond]',
    doc = 'Builds an index. A WHERE clause makes it partial, covering only matching rows - much smaller when you query one hot subset.' },
  ['CONCURRENTLY'] = { kind = K, sig = 'CREATE INDEX CONCURRENTLY ...',
    doc = 'Builds without blocking writes, at the cost of two table passes. Cannot run inside a transaction block, so sqlx migrations need this statement in a file of its own.' },
  ['CREATE TYPE'] = { kind = K, sig = "CREATE TYPE name AS ENUM ('a', 'b') | AS (field type, ...)",
    doc = 'Defines an enum or composite type. Enum labels can be added later but not removed, and until PG12 ADD VALUE could not run inside a transaction.' },
  ['CREATE FUNCTION'] = { kind = K, sig = 'CREATE [OR REPLACE] FUNCTION name(args) RETURNS type LANGUAGE lang AS $$ body $$',
    doc = 'Defines a function. OR REPLACE keeps the existing signature - changing argument types creates an overload instead of replacing.' },
  ['RETURNS'] = { kind = K, sig = 'RETURNS type | RETURNS TABLE(col type, ...) | RETURNS SETOF type',
    doc = 'Result type of a function. A trigger function must return `trigger`.' },
  ['LANGUAGE'] = { kind = K, sig = 'LANGUAGE { sql | plpgsql | c }',
    doc = 'Which language the body is written in. `sql` bodies can be inlined by the planner, `plpgsql` bodies never are.' },
  ['IMMUTABLE'] = { kind = K, sig = 'CREATE FUNCTION ... IMMUTABLE',
    doc = 'Promises the same result for the same arguments forever, with no database reads. Required to use the function in an index expression - and lying here corrupts indexes.' },
  ['STABLE'] = { kind = K, sig = 'CREATE FUNCTION ... STABLE',
    doc = 'Promises a constant result within one statement; may read the database. The right marker for a lookup function.' },
  ['VOLATILE'] = { kind = K, sig = 'CREATE FUNCTION ... VOLATILE',
    doc = 'The default: may return anything and may have side effects, so the planner never folds or caches calls.' },
  ['SECURITY DEFINER'] = { kind = K, sig = 'CREATE FUNCTION ... SECURITY DEFINER',
    doc = 'Runs with the privileges of the owner rather than the caller. Set an explicit `search_path` on such a function or a caller can hijack unqualified names.' },
  ['CREATE TRIGGER'] = { kind = K, sig = 'CREATE TRIGGER name { BEFORE | AFTER } event ON table FOR EACH ROW EXECUTE FUNCTION f()',
    doc = 'Attaches a function to a table event. Row triggers see NEW and OLD; the function takes no arguments in its signature.' },
  ['BEFORE'] = { kind = K, sig = 'BEFORE INSERT OR UPDATE [OF col] ON table',
    doc = 'Fires before the row is written, so the function can modify NEW or cancel the write by returning NULL.' },
  ['AFTER'] = { kind = K, sig = 'AFTER INSERT OR UPDATE OR DELETE ON table',
    doc = 'Fires once the row is written; the return value is ignored. On DELETE the row is already gone, which is why a foreign key back to it must be NULL by then.' },
  ['FOR EACH ROW'] = { kind = K, sig = 'CREATE TRIGGER ... FOR EACH ROW',
    doc = 'Runs the function per affected row, with NEW/OLD populated. The alternative, FOR EACH STATEMENT, runs once and sees neither.' },
  ['EXECUTE FUNCTION'] = { kind = K, sig = 'CREATE TRIGGER ... EXECUTE FUNCTION name(args)',
    doc = 'Names the trigger function. Any arguments here arrive as text in TG_ARGV, not as declared parameters.' },
  ['CREATE EXTENSION'] = { kind = K, sig = 'CREATE EXTENSION [IF NOT EXISTS] name',
    doc = 'Loads a packaged extension (pgcrypto, uuid-ossp, unaccent, pg_trgm) into the current database.' },
  ['MATERIALIZED VIEW'] = { kind = K, sig = 'CREATE MATERIALIZED VIEW name AS query',
    doc = 'A view whose result is stored on disk. Stale until REFRESH MATERIALIZED VIEW, which locks it out unless run CONCURRENTLY - and that needs a unique index.' },

  -- aggregates ----------------------------------------------------------------
  ['COUNT'] = { kind = F, sig = 'count(*) | count(expr) | count(DISTINCT expr) -> bigint',
    doc = 'count(*) counts rows; count(expr) counts non-NULL values, which is how you count a subset without a CASE. Returns 0, never NULL, for an empty input.' },
  ['SUM'] = { kind = F, sig = 'sum(expr) -> numeric | bigint | double',
    doc = 'Adds non-NULL values. Returns NULL, not 0, when there is nothing to add - wrap in coalesce() if a number is required.' },
  ['AVG'] = { kind = F, sig = 'avg(expr) -> numeric | double', doc = 'Mean of non-NULL values; NULL for an empty set.' },
  ['MIN'] = { kind = F, sig = 'min(expr) -> same type', doc = 'Smallest non-NULL value.' },
  ['MAX'] = { kind = F, sig = 'max(expr) -> same type', doc = 'Largest non-NULL value.' },
  ['ARRAY_AGG'] = { kind = F, sig = 'array_agg(expr [ORDER BY ...]) -> array',
    doc = 'Collects values into an array, in an order you should state explicitly. NULLs are kept, so the array can contain NULL elements.' },
  ['STRING_AGG'] = { kind = F, sig = 'string_agg(expr, delimiter [ORDER BY ...]) -> text',
    doc = 'Joins values with a separator, skipping NULLs.' },
  ['JSON_AGG'] = { kind = F, sig = 'json_agg(expr [ORDER BY ...]) -> json', doc = 'Collects values into a JSON array.' },
  ['JSONB_AGG'] = { kind = F, sig = 'jsonb_agg(expr [ORDER BY ...]) -> jsonb',
    doc = 'Collects values into a jsonb array. With `jsonb_agg(t)` over a table alias you get one JSON object per row - the usual way to return nested data in one query.' },
  ['JSONB_OBJECT_AGG'] = { kind = F, sig = 'jsonb_object_agg(key, value) -> jsonb', doc = 'Builds a jsonb object from key/value pairs.' },
  ['BOOL_AND'] = { kind = F, sig = 'bool_and(expr) -> boolean', doc = 'True when every non-NULL input is true.' },
  ['BOOL_OR'] = { kind = F, sig = 'bool_or(expr) -> boolean', doc = 'True when at least one non-NULL input is true.' },

  -- conditionals --------------------------------------------------------------
  ['COALESCE'] = { kind = F, sig = 'coalesce(value [, ...]) -> value',
    doc = 'First non-NULL argument. Evaluation is left to right and stops at the first hit, so an expensive fallback is not computed when it is not needed. All arguments must share a common type.' },
  ['NULLIF'] = { kind = F, sig = 'nullif(a, b) -> value',
    doc = 'NULL when the two are equal, otherwise `a`. The usual guard against division by zero: `a / nullif(b, 0)`.' },
  ['GREATEST'] = { kind = F, sig = 'greatest(a, b, ...) -> value', doc = 'Largest argument, ignoring NULLs (unlike max(), this works across columns of one row).' },
  ['LEAST'] = { kind = F, sig = 'least(a, b, ...) -> value', doc = 'Smallest argument, ignoring NULLs.' },

  -- strings -------------------------------------------------------------------
  ['CONCAT'] = { kind = F, sig = 'concat(a, b, ...) -> text',
    doc = 'Joins arguments, treating NULL as an empty string - unlike `||`, where one NULL makes the whole result NULL.' },
  ['CONCAT_WS'] = { kind = F, sig = 'concat_ws(sep, a, b, ...) -> text', doc = 'Joins with a separator, skipping NULL arguments.' },
  ['FORMAT'] = { kind = F, sig = 'format(fmt, args...) -> text',
    doc = "Sprintf-style formatting. `%I` quotes an identifier and `%L` quotes a literal, which is the only safe way to build dynamic SQL for EXECUTE." },
  ['LENGTH'] = { kind = F, sig = 'length(string) -> int', doc = 'Number of characters (not bytes) in the string.' },
  ['SUBSTRING'] = { kind = F, sig = 'substring(string FROM start FOR count) | substring(string FROM pattern)',
    doc = 'Extracts a slice by position, or the first regex match. Positions are 1-based.' },
  ['POSITION'] = { kind = F, sig = 'position(needle IN haystack) -> int', doc = '1-based index of the first occurrence, or 0 when absent.' },
  ['STRPOS'] = { kind = F, sig = 'strpos(haystack, needle) -> int', doc = 'Same as position(), with plain function arguments.' },
  ['TRIM'] = { kind = F, sig = 'trim([LEADING | TRAILING | BOTH] [chars] FROM string) -> text',
    doc = 'Strips characters from the ends - by default spaces only, so tabs and newlines survive unless you pass an explicit set.' },
  ['BTRIM'] = { kind = F, sig = 'btrim(string [, chars]) -> text', doc = 'Strips any of `chars` from both ends; defaults to spaces.' },
  ['UPPER'] = { kind = F, sig = 'upper(string) -> text', doc = 'Uppercases, according to the database collation.' },
  ['LOWER'] = { kind = F, sig = 'lower(string) -> text', doc = 'Lowercases, according to the database collation.' },
  ['INITCAP'] = { kind = F, sig = 'initcap(string) -> text', doc = 'Uppercases the first letter of each word, lowercases the rest.' },
  ['REPLACE'] = { kind = F, sig = 'replace(string, from, to) -> text', doc = 'Replaces every literal occurrence - no pattern matching.' },
  ['SPLIT_PART'] = { kind = F, sig = 'split_part(string, delimiter, n) -> text', doc = 'The n-th field when split on a delimiter, 1-based; empty string when out of range.' },
  ['REGEXP_REPLACE'] = { kind = F, sig = "regexp_replace(string, pattern, replacement [, flags]) -> text",
    doc = "Replaces the first match, or all with flag `g`. `\\1` refers to a capture group." },
  ['REGEXP_MATCH'] = { kind = F, sig = 'regexp_match(string, pattern [, flags]) -> text[]',
    doc = 'Array of capture groups from the first match, or NULL when there is none.' },
  ['REGEXP_SPLIT_TO_ARRAY'] = { kind = F, sig = 'regexp_split_to_array(string, pattern) -> text[]', doc = 'Splits on a regex into an array.' },
  ['LPAD'] = { kind = F, sig = 'lpad(string, length [, fill]) -> text', doc = 'Left-pads to a length, truncating when already longer.' },
  ['RPAD'] = { kind = F, sig = 'rpad(string, length [, fill]) -> text', doc = 'Right-pads to a length, truncating when already longer.' },
  ['LEFT'] = { kind = F, sig = 'left(string, n) -> text', doc = 'First n characters; a negative n drops that many from the end.' },
  ['RIGHT'] = { kind = F, sig = 'right(string, n) -> text', doc = 'Last n characters.' },
  ['STARTS_WITH'] = { kind = F, sig = 'starts_with(string, prefix) -> boolean', doc = 'Prefix test without LIKE pattern escaping.' },
  ['MD5'] = { kind = F, sig = 'md5(string) -> text', doc = 'MD5 as a hex string. Fine as a change fingerprint, unsuitable for passwords.' },
  ['ENCODE'] = { kind = F, sig = "encode(bytea, 'base64' | 'hex' | 'escape') -> text", doc = 'Renders binary data as text.' },
  ['DECODE'] = { kind = F, sig = "decode(text, 'base64' | 'hex' | 'escape') -> bytea", doc = 'Parses encoded text back to binary.' },
  ['UNACCENT'] = { kind = F, sig = 'unaccent(string) -> text',
    doc = 'Folds accented characters to ASCII; needs the unaccent extension. Not immutable as installed, so indexing it requires an immutable wrapper.' },
  ['TO_CHAR'] = { kind = F, sig = "to_char(value, format) -> text", doc = "Formats a timestamp or number, e.g. to_char(t, 'YYYY-MM-DD')." },

  -- dates ---------------------------------------------------------------------
  ['NOW'] = { kind = F, sig = 'now() -> timestamptz',
    doc = 'Start time of the current transaction - constant for its whole duration, so every row inserted in one transaction shares it. Use clock_timestamp() for the real wall clock.' },
  ['CURRENT_TIMESTAMP'] = { kind = F, sig = 'current_timestamp -> timestamptz', doc = 'Standard-SQL spelling of now(); also transaction start time.' },
  ['CURRENT_DATE'] = { kind = F, sig = 'current_date -> date', doc = "Today's date in the session time zone." },
  ['CLOCK_TIMESTAMP'] = { kind = F, sig = 'clock_timestamp() -> timestamptz', doc = 'Actual current time, advancing within a transaction - the one to use for measuring elapsed time.' },
  ['AGE'] = { kind = F, sig = 'age(a [, b]) -> interval', doc = 'Interval between two timestamps in years/months/days; with one argument, from current_date.' },
  ['DATE_TRUNC'] = { kind = F, sig = "date_trunc('day' | 'hour' | ..., timestamp [, timezone]) -> timestamp",
    doc = 'Rounds a timestamp down to a unit. For timestamptz the result depends on the session time zone unless you pass one explicitly.' },
  ['DATE_PART'] = { kind = F, sig = "date_part('year' | 'epoch' | ..., source) -> double", doc = 'Function form of EXTRACT.' },
  ['EXTRACT'] = { kind = F, sig = 'EXTRACT(field FROM source) -> numeric', doc = "Pulls one field out of a timestamp or interval; `EXTRACT(EPOCH FROM x)` gives seconds." },
  ['TO_TIMESTAMP'] = { kind = F, sig = 'to_timestamp(epoch_seconds) | to_timestamp(text, format) -> timestamptz',
    doc = 'Converts a Unix epoch or a formatted string to a timestamp.' },
  ['AT TIME ZONE'] = { kind = K, sig = 'timestamp AT TIME ZONE zone',
    doc = 'Reinterprets between timestamp and timestamptz: applied to timestamptz it gives the local wall time in that zone, applied to a bare timestamp it declares which zone it was in.' },
  -- json ----------------------------------------------------------------------
  ['TO_JSONB'] = { kind = F, sig = 'to_jsonb(anyelement) -> jsonb', doc = 'Converts any value, including a whole row, to jsonb.' },
  ['JSONB_BUILD_OBJECT'] = { kind = F, sig = 'jsonb_build_object(key, value, ...) -> jsonb',
    doc = 'Builds an object from alternating keys and values, keeping each value type intact.' },
  ['JSONB_BUILD_ARRAY'] = { kind = F, sig = 'jsonb_build_array(value, ...) -> jsonb', doc = 'Builds a jsonb array from the arguments.' },
  ['JSONB_SET'] = { kind = F, sig = "jsonb_set(target, path text[], new_value [, create_missing]) -> jsonb",
    doc = 'Returns a copy with one path replaced. A NULL argument makes the whole result NULL, which quietly wipes the column in an UPDATE.' },
  ['JSONB_ARRAY_ELEMENTS'] = { kind = F, sig = 'jsonb_array_elements(jsonb) -> setof jsonb',
    doc = 'Expands a JSON array into rows. Use in FROM (often with CROSS JOIN LATERAL), not in the target list.' },
  ['JSONB_ARRAY_LENGTH'] = { kind = F, sig = 'jsonb_array_length(jsonb) -> int', doc = 'Element count of a JSON array; errors on a non-array.' },
  ['JSONB_TYPEOF'] = { kind = F, sig = "jsonb_typeof(jsonb) -> text", doc = "Type name of the value: object, array, string, number, boolean or null." },
  ['JSONB_EACH'] = { kind = F, sig = 'jsonb_each(jsonb) -> setof (key text, value jsonb)', doc = 'Expands an object into key/value rows.' },
  ['ROW_TO_JSON'] = { kind = F, sig = 'row_to_json(record) -> json', doc = 'Converts a row to a JSON object; to_jsonb() is usually preferable.' },

  -- arrays --------------------------------------------------------------------
  ['UNNEST'] = { kind = F, sig = 'unnest(array [, ...]) -> setof element',
    doc = 'Expands an array into rows. With several arrays it zips them side by side, padding the short ones with NULL - the trick behind bulk INSERT ... SELECT from sqlx slices.' },
  ['ARRAY_LENGTH'] = { kind = F, sig = 'array_length(array, dimension) -> int',
    doc = 'Length along a dimension (pass 1 for a normal array). Returns NULL, not 0, for an empty array - cardinality() gives 0.' },
  ['CARDINALITY'] = { kind = F, sig = 'cardinality(array) -> int', doc = 'Total element count across all dimensions; 0 for an empty array.' },
  ['ARRAY_POSITION'] = { kind = F, sig = 'array_position(array, element) -> int', doc = '1-based index of the first occurrence, or NULL.' },
  ['ARRAY_REMOVE'] = { kind = F, sig = 'array_remove(array, element) -> array', doc = 'Copy without any element equal to the given one.' },
  ['ARRAY_TO_STRING'] = { kind = F, sig = 'array_to_string(array, delimiter [, null_string]) -> text', doc = 'Joins elements; NULLs are dropped unless a replacement is given.' },
  ['STRING_TO_ARRAY'] = { kind = F, sig = 'string_to_array(text, delimiter) -> text[]', doc = 'Splits a string into an array.' },
  ['ARRAY'] = { kind = K, sig = 'ARRAY[expr, ...] | ARRAY(subquery) | declared as type[]', rust = 'Vec<T>',
    doc = 'Array constructor; every type also has an array form written `type[]`. The subquery form collapses a result set into one value, indexes are 1-based, and declared dimensions are not enforced. `= ANY($1)` is how a Rust Vec becomes an IN list.' },

  -- ids, series, sequences ----------------------------------------------------
  ['GEN_RANDOM_UUID'] = { kind = F, sig = 'gen_random_uuid() -> uuid',
    doc = 'Random v4 UUID, built in since PG13 (no extension needed). Random order makes it a poor clustering key for very large tables.' },
  ['UUID_GENERATE_V4'] = { kind = F, sig = 'uuid_generate_v4() -> uuid', doc = 'Same, from the uuid-ossp extension; gen_random_uuid() is the modern choice.' },
  ['GENERATE_SERIES'] = { kind = F, sig = 'generate_series(start, stop [, step]) -> setof',
    doc = 'Produces a row per step, over numbers or timestamps. The standard way to fill gaps in a time series before a LEFT JOIN.' },
  ['NEXTVAL'] = { kind = F, sig = "nextval('sequence') -> bigint",
    doc = 'Advances a sequence and returns the value. Not transactional - a rollback still consumes the number, so sequences have gaps.' },
  ['RANDOM'] = { kind = F, sig = 'random() -> double precision', doc = 'Uniform value in [0,1). `ORDER BY random()` sorts the whole table, so it is fine for small sets only.' },

  -- full text -----------------------------------------------------------------
  ['TO_TSVECTOR'] = { kind = F, sig = "to_tsvector([config,] text) -> tsvector",
    doc = 'Normalises text into searchable lexemes. Always pass an explicit configuration in an index expression, or the index depends on a session setting and is not immutable.' },
  ['TO_TSQUERY'] = { kind = F, sig = "to_tsquery([config,] query) -> tsquery",
    doc = 'Parses an operator syntax (`&`, `|`, `!`, `<->`), and errors on malformed input - so it must not receive raw user text.' },
  ['PLAINTO_TSQUERY'] = { kind = F, sig = 'plainto_tsquery([config,] text) -> tsquery', doc = 'Treats input as plain words joined by AND; safe for user input.' },
  ['WEBSEARCH_TO_TSQUERY'] = { kind = F, sig = 'websearch_to_tsquery([config,] text) -> tsquery',
    doc = 'Parses web-search syntax - quoted phrases, `or`, leading `-`. Never errors, so it is the right entry point for a search box.' },
  ['TS_RANK'] = { kind = F, sig = 'ts_rank([weights,] tsvector, tsquery) -> float4',
    doc = 'Relevance score for ordering matches. Computed per row after matching, so it cannot use an index.' },

  -- plpgsql -------------------------------------------------------------------
  ['DECLARE'] = { kind = K, sig = 'DECLARE name type [:= default];',
    doc = 'Variable block of a PL/pgSQL body, between the signature and BEGIN.' },
  ['RAISE'] = { kind = K, sig = "RAISE [level] 'format %', arg [USING ERRCODE = '...'];",
    doc = 'Emits a message. EXCEPTION aborts the transaction, NOTICE/WARNING only log. `%` is the placeholder - there is no positional index.' },
  ['NEW'] = { kind = K, sig = 'NEW.column',
    doc = 'In a row trigger, the incoming row. NULL on DELETE. A BEFORE trigger may modify it and must return it for the change to stick.' },
  ['OLD'] = { kind = K, sig = 'OLD.column', doc = 'In a row trigger, the row as it was. NULL on INSERT.' },
  ['TG_OP'] = { kind = K, sig = "TG_OP -> text",
    doc = "Which event fired the trigger: 'INSERT', 'UPDATE', 'DELETE' or 'TRUNCATE'. Lets one function serve several events." },
  ['PERFORM'] = { kind = K, sig = 'PERFORM query;',
    doc = 'Runs a query for its side effects and discards the result. PL/pgSQL rejects a bare SELECT whose result goes nowhere, so this is how you call a function for effect.' },
  ['EXECUTE'] = { kind = K, sig = 'EXECUTE format(...) [INTO var] [USING params];',
    doc = 'Runs dynamically built SQL. Pass values through USING rather than interpolating them, and quote identifiers with %I in format().' },
  ['RETURN QUERY'] = { kind = K, sig = 'RETURN QUERY query;', doc = 'Appends a query result to the output of a set-returning function; execution continues.' },
  ['FOUND'] = { kind = K, sig = 'IF NOT FOUND THEN ... END IF;', doc = 'Boolean set after each query: whether it affected or returned any row.' },
  ['EXCEPTION'] = { kind = K, sig = 'EXCEPTION WHEN unique_violation THEN ...',
    doc = 'Error handler at the end of a block. Entering one costs a subtransaction, so a handler inside a hot loop is expensive.' },

  -- types ---------------------------------------------------------------------
  -- `rust` is what sqlx decodes the type into, which is usually the reason a cast is
  -- there at all: `latitude::FLOAT8` exists to get an f64 instead of a BigDecimal.

  ['SMALLINT'] = { kind = T, sig = 'smallint (int2) - 2 bytes, -32768 .. 32767', rust = 'i16',
    doc = 'Small signed integer. Worth it only for very wide tables; alignment often eats the saving.' },
  ['INT2'] = { kind = T, sig = 'int2 - alias of smallint', rust = 'i16', doc = 'Internal name for smallint.' },
  ['INTEGER'] = { kind = T, sig = 'integer (int, int4) - 4 bytes, about -2.15e9 .. 2.15e9', rust = 'i32',
    doc = 'The default integer. An id column that may exceed two billion rows wants bigint instead - widening it later rewrites the table.' },
  ['INT'] = { kind = T, sig = 'int - alias of integer', rust = 'i32', doc = 'Alias of integer, 4 bytes.' },
  ['INT4'] = { kind = T, sig = 'int4 - alias of integer', rust = 'i32', doc = 'Internal name for integer.' },
  ['BIGINT'] = { kind = T, sig = 'bigint (int8) - 8 bytes', rust = 'i64',
    doc = 'Large signed integer. Note that Postgres has no unsigned types, so a Rust u64 has no direct counterpart.' },
  ['INT8'] = { kind = T, sig = 'int8 - alias of bigint', rust = 'i64', doc = 'Internal name for bigint.' },
  ['SERIAL'] = { kind = T, sig = 'serial - integer + sequence default', rust = 'i32',
    doc = 'Not a real type: shorthand for integer with a nextval() default and an owned sequence. GENERATED AS IDENTITY is the standard replacement.' },
  ['BIGSERIAL'] = { kind = T, sig = 'bigserial - bigint + sequence default', rust = 'i64',
    doc = 'Shorthand for bigint with an owned sequence.' },
  ['NUMERIC'] = { kind = T, sig = 'numeric(precision, scale) - exact, arbitrary precision', rust = 'BigDecimal / Decimal',
    doc = 'Exact decimal arithmetic, the right type for money. Slow compared to integers and floats, and sqlx needs the bigdecimal or rust_decimal feature to decode it - hence the common `::FLOAT8` cast when exactness does not matter.' },
  ['DECIMAL'] = { kind = T, sig = 'decimal - alias of numeric', rust = 'BigDecimal / Decimal', doc = 'Alias of numeric.' },
  ['REAL'] = { kind = T, sig = 'real (float4) - 4 bytes, ~6 digits', rust = 'f32',
    doc = 'Single-precision float. Inexact - never use for money.' },
  ['FLOAT4'] = { kind = T, sig = 'float4 - alias of real', rust = 'f32', doc = 'Internal name for real.' },
  ['DOUBLE PRECISION'] = { kind = T, sig = 'double precision (float8) - 8 bytes, ~15 digits', rust = 'f64',
    doc = 'Double-precision float. Inexact, but fast and directly decodable, which is why numeric columns are often cast to it on the way out.' },
  ['FLOAT8'] = { kind = T, sig = 'float8 - alias of double precision', rust = 'f64',
    doc = 'Internal name for double precision. `value::FLOAT8` is the usual way to hand sqlx an f64 from a numeric column.' },
  ['MONEY'] = { kind = T, sig = 'money - 8 bytes, fixed fractional precision', rust = 'PgMoney',
    doc = 'Locale-dependent currency type. Its output format follows lc_monetary, so numeric is the safer choice.' },

  ['TEXT'] = { kind = T, sig = 'text - variable length, unlimited', rust = 'String / &str',
    doc = 'The default string type. No performance penalty against varchar in Postgres, so a length limit is a constraint choice, not an optimisation.' },
  ['VARCHAR'] = { kind = T, sig = 'varchar(n) - variable length with a limit', rust = 'String / &str',
    doc = 'Text with a maximum length, enforced on write. Stored identically to text; raising the limit is cheap, lowering it rewrites the table.' },
  ['CHARACTER VARYING'] = { kind = T, sig = 'character varying(n) - the standard spelling of varchar', rust = 'String / &str',
    doc = 'Standard-SQL name for varchar.' },
  ['CHAR'] = { kind = T, sig = 'char(n) - blank-padded fixed length', rust = 'String',
    doc = 'Pads values to n with spaces and strips them on read, which surprises comparisons. Rarely what you want.' },
  ['BYTEA'] = { kind = T, sig = 'bytea - variable-length binary', rust = 'Vec<u8> / &[u8]',
    doc = 'Raw bytes. Rendered as hex by default, and the whole value is read at once - large blobs belong outside the database.' },
  ['CITEXT'] = { kind = T, sig = 'citext - case-insensitive text (extension)', rust = 'String',
    doc = 'Text that compares case-insensitively, from the citext extension. Avoids scattering lower() through queries and indexes.' },

  ['BOOLEAN'] = { kind = T, sig = 'boolean (bool) - true, false or NULL', rust = 'bool',
    doc = 'Three-valued: a NULL boolean is neither true nor false, so `WHERE flag` silently drops those rows.' },
  ['BOOL'] = { kind = T, sig = 'bool - alias of boolean', rust = 'bool', doc = 'Alias of boolean.' },

  ['UUID'] = { kind = T, sig = 'uuid - 16 bytes', rust = 'uuid::Uuid',
    doc = 'Fixed 128-bit identifier, stored binary rather than as its 36-character text form. Needs the uuid feature in sqlx.' },
  ['JSON'] = { kind = T, sig = 'json - stored as text', rust = 'serde_json::Value / Json<T>',
    doc = 'Keeps the exact input text, whitespace and key order included, and reparses on every access. Prefer jsonb unless you need the original bytes back.' },
  ['JSONB'] = { kind = T, sig = 'jsonb - decomposed binary', rust = 'serde_json::Value / Json<T>',
    doc = 'Parsed on write, so reads are cheap and it supports GIN indexing and containment (@>). Duplicate keys are dropped and key order is not preserved.' },
  ['XML'] = { kind = T, sig = 'xml - checked XML text', rust = 'String', doc = 'Text validated as well-formed XML on write.' },

  ['TIMESTAMPTZ'] = { kind = T, sig = 'timestamptz - 8 bytes, instant in time', rust = 'DateTime<Utc> / OffsetDateTime',
    doc = 'Despite the name it stores no zone: the input is converted to UTC and rendered back in the session TimeZone. This is the type almost every application wants.' },
  ['TIMESTAMP WITH TIME ZONE'] = { kind = T, sig = 'timestamp with time zone - the standard spelling of timestamptz',
    rust = 'DateTime<Utc> / OffsetDateTime', doc = 'Standard-SQL name for timestamptz.' },
  ['TIMESTAMP'] = { kind = T, sig = 'timestamp - 8 bytes, wall-clock reading', rust = 'NaiveDateTime / PrimitiveDateTime',
    doc = 'A date and time with no zone at all, so two values are only comparable if you know they share one. Bare `timestamp` in a migration is usually a mistake for timestamptz.' },
  ['DATE'] = { kind = T, sig = 'date - 4 bytes, calendar day', rust = 'NaiveDate / time::Date',
    doc = 'A day with no time or zone.' },
  ['TIME'] = { kind = T, sig = 'time - 8 bytes, time of day', rust = 'NaiveTime / time::Time',
    doc = 'Time of day without a date.' },
  ['INTERVAL'] = { kind = T, sig = "interval - 16 bytes; literal: INTERVAL '1 day', INTERVAL '2 hours 30 min'",
    rust = 'PgInterval',
    doc = 'A duration held as separate months, days and microseconds, so it is calendar-aware: adding one month is not a fixed number of seconds, and a day is not always 24 hours across a DST boundary.' },

  ['INET'] = { kind = T, sig = 'inet - host address, optionally with a netmask', rust = 'IpAddr / IpNetwork',
    doc = 'IPv4 or IPv6 address. Understands subnet containment operators, unlike text.' },
  ['CIDR'] = { kind = T, sig = 'cidr - network address', rust = 'IpNetwork',
    doc = 'A network specification; unlike inet it rejects bits set to the right of the netmask.' },

  ['TSVECTOR'] = { kind = T, sig = 'tsvector - sorted list of lexemes', rust = 'String',
    doc = 'Normalised document for full-text search, built by to_tsvector(). Match it with @@ and index it with GIN.' },
  ['TSQUERY'] = { kind = T, sig = 'tsquery - full-text search expression', rust = 'String',
    doc = 'Parsed search terms with the operators &, |, ! and <->.' },

  ['TRIGGER'] = { kind = T, sig = 'RETURNS trigger',
    doc = 'Pseudo-type for trigger functions. The function takes no declared arguments and returns NEW, OLD, or NULL to cancel the row in a BEFORE trigger.' },
  ['RECORD'] = { kind = T, sig = 'RETURNS record | RETURNS SETOF record',
    doc = 'An anonymous row type. A caller must supply a column definition list, so RETURNS TABLE(...) is usually friendlier.' },
  ['VOID'] = { kind = T, sig = 'RETURNS void', rust = '()', doc = 'No result. A function returning void is called for its side effects.' },

  -- operators -----------------------------------------------------------------
  ['||'] = { kind = O, sig = 'a || b',
    doc = 'Concatenates strings, arrays or jsonb. With a NULL operand the whole result is NULL - concat() is the forgiving version.' },
  ['::'] = { kind = O, sig = 'expr::type', doc = 'Postgres cast shorthand. Binds tightly, so `a::text || b` casts only `a`.' },
  ['->'] = { kind = O, sig = "json -> 'key' | json -> index", doc = 'Extracts a JSON member as json/jsonb, so it can be chained.' },
  ['->>'] = { kind = O, sig = "json ->> 'key'", doc = 'Extracts a JSON member as text. Terminal - the result is no longer JSON.' },
  ['#>'] = { kind = O, sig = "json #> '{a,b}'", doc = 'Extracts at a path as jsonb.' },
  ['#>>'] = { kind = O, sig = "json #>> '{a,b}'", doc = 'Extracts at a path as text.' },
  ['@>'] = { kind = O, sig = 'a @> b', doc = 'Containment: left contains right. Works for jsonb, arrays and ranges, and is GIN-indexable.' },
  ['<@'] = { kind = O, sig = 'a <@ b', doc = 'Contained by - the mirror of @>.' },
  ['&&'] = { kind = O, sig = 'a && b', doc = 'Overlap: the arrays or ranges share at least one element. GIN-indexable.' },
  ['@@'] = { kind = O, sig = 'tsvector @@ tsquery', doc = 'Full-text match. The operator a GIN index on the tsvector answers.' },
  ['~'] = { kind = O, sig = 'string ~ pattern', doc = 'Case-sensitive POSIX regex match. `~*` ignores case, `!~` negates.' },
  ['~*'] = { kind = O, sig = 'string ~* pattern', doc = 'Case-insensitive POSIX regex match.' },
}
