-- Custom quotes for vim-startify dashboard, appended to the built-in list.
-- Each quote is a list of lines:
--   { 'Text', '', '- Author' }      -- with author (empty string adds spacing)
--   { 'Single line without author' }
--   { 'Line 1', 'Line 2', '', '- Author' }

return {
  {'Premature optimization is the root of all evil.', '', '- Donald Knuth'},
  {'Simplicity is prerequisite for reliability.', '', '- Edsger W. Dijkstra'},
  {'Rules of Optimization:',
   '  Rule 1: Dont do it.',
   '  Rule 2 (for experts only): Dont do it yet.', '',
   '- Michael A. Jackson'},
  {'Talk is cheap. Show me the code.', '', '- Linus Torvalds'},
  {'Bad programmers worry about the code.',
   'Good programmers worry about data structures',
   'and their relationships.', '', '- Linus Torvalds'},
  {'Theory and practice sometimes clash.',
   'And when that happens, theory loses.',
   'Every single time.', '', '- Linus Torvalds'},
  {'Intelligence is the ability to avoid doing work,',
   'yet getting the work done.', '', '- Linus Torvalds'},
  {"I am not a visionary. I'm an engineer.", '', '- Linus Torvalds'},
  {'There are only two kinds of languages:',
   'the ones people complain about',
   'and the ones nobody uses.', '', '- Bjarne Stroustrup'},
  {'C makes it easy to shoot yourself in the foot;',
   'C++ makes it harder, but when you do',
   'it blows your whole leg off.', '', '- Bjarne Stroustrup'},
  {'Anybody who comes to you and says',
   'he has a perfect language',
   'is either naive or a salesman.', '', '- Bjarne Stroustrup'},
  {'Design and programming are human activities;',
   'forget that and all is lost.', '', '- Bjarne Stroustrup'},
  {'The most important single aspect of software development',
   'is to be clear about what you are trying to build.', '', '- Bjarne Stroustrup'},
  {'A program that has not been tested does not work.', '', '- Bjarne Stroustrup'},
  {"I called this technique",
   "'resource acquisition is initialization'.", '',
   '- Bjarne Stroustrup, The Design and Evolution of C++'},
  {'The basic idea is to represent a resource by a local object,',
   "so that the local object's destructor",
   'will release the resource.', '',
   '- Bjarne Stroustrup, on RAII'},
  {'In realistic systems, there are far more',
   'resource acquisitions than kinds of resources,',
   'so RAII leads to less code than a finally construct.', '',
   '- Bjarne Stroustrup'},
  {'You should throw an exception from a constructor',
   'whenever you cannot properly initialize an object.',
   'There is no really satisfactory alternative',
   'to exiting a constructor by a throw.', '',
   '- Bjarne Stroustrup'},
  {'RAII is one of the most clever techniques in C++.', '',
   '- C++ folklore'},
  {'C++ is its own best garbage collector.', '',
   '- C++ folklore'},
  {"C++ doesn't need a garbage collector -",
   'it sits in front of the screen.', '',
   '- C++ folklore'},
  {'Java developers have garbage collection.',
   'C++ developers ARE garbage collectors.', '',
   '- C++ folklore'},
  {'The free lunch is over.', '', '- Herb Sutter'},
  {'It is far, far easier to make a correct program fast',
   'than to make a fast program correct.', '', '- Herb Sutter'},
  {'Premature pessimization is as bad as premature optimization.', '',
   '- Herb Sutter & Andrei Alexandrescu'},
  {'Prefer constants over variables wherever it is sensible,',
   'and make const your default choice',
   'when you define a value.', '', '- Herb Sutter'},
  {'Prefer to use standard library algorithms',
   'instead of writing your own loops.', '', '- Herb Sutter'},
  {'Prefer brief single-purpose functions,',
   'small single-purpose classes,',
   'and cohesive modules.', '', '- Herb Sutter'},
  {'Use const proactively.', '', '- Herb Sutter'},
  {'There are only two hard things in Computer Science:',
   'cache invalidation and naming things.', '', '- Phil Karlton'},
  {'There are 2 hard problems in computer science:',
   'cache invalidation, naming things,',
   'and off-by-one errors.', '', '- Leon Bambrick'},
  {"Hofstadter's Law: It always takes longer",
   'than you expect, even when you take into',
   "account Hofstadter's Law.", '', '- Douglas Hofstadter'},
  {'The most dangerous phrase in the language is:',
   "\"We've always done it this way.\"", '', '- Grace Hopper'},
  {'Programming today is a race between software engineers',
   'striving to build bigger and better idiot-proof programs,',
   'and the Universe trying to produce bigger and better idiots.',
   'So far, the Universe is winning.', '', '- Rick Cook'},
  {'A computer once beat me at chess,',
   'but it was no match for me at kick boxing.', '', '- Emo Philips'},
  {"Code is like humor. When you have to explain it, it's bad.", '',
   '- Cory House'},
  {'The trouble with programmers is that you can never',
   "tell what a programmer is doing until it's too late.", '',
   '- Seymour Cray'},
  {'Hardware: the parts of a computer system',
   'that can be kicked.', '', '- Jeff Pesis'},
  {'Weeks of programming can save you hours of planning.'},
  {'Software and cathedrals are much the same:',
   'first we build them, then we pray.'},
  {"It's not a bug - it's an undocumented feature."},
  {'Technology from the past come to save',
   'the future from itself.', '', '- Graydon Hoare, creator of Rust'},
  {'Memory safety without garbage collection,',
   'concurrency without data races,',
   'abstractions without overhead.', '', '- The Rust Book'},
  {'Fearless concurrency is a better pitch for Rust',
   'than memory safety.', '', '- Steve Klabnik'},
  {'If C is knives and C++ is chainsaws,',
   'Rust is parkour with gear.', '', '- Llogiq'},
  {'If it compiles, it works.', '', '- Rust folklore'},
  {'I came for the performance,',
   'I stayed for the borrow checker.', '', '- Rust folklore'},
  {'Fighting the borrow checker', 'is a rite of passage.', '',
   '- Rust folklore'},
  {'The borrow checker is my sidekick,',
   "making sure I don't shoot myself in the foot.", '', '- Rust folklore'},
  {'rustc is like a friend trying to help you write better code,',
   'rather than a gatekeeper working to slow you down.', '',
   '- Rust folklore'},
  {'Blazingly fast.', '', '- Every Rust README'},
  {'Zero-cost abstractions:',
   "what you don't use, you don't pay for,",
   'and what you do use, you could not hand-code any better.', '',
   '- Bjarne Stroustrup (adopted by Rust)'},
  {'Rewrite it in Rust.', '', '- RIIR, the eternal meme'},
  {'In Rust we trust.', '',
   '- US White House Office (on memory safety, 2024)'},
  {'Safety clears the biggest obstacle preventing people',
   'from becoming systems programmers.', '', '- Dave Herman, Mozilla'},
  {'Rust is one of the first languages in a long time',
   'that makes you think different.', '', '- agentgt'},
  {'ADTs are simply the best way',
   'to represent state and data.', '', '- vvanders'},
  {'Refactoring is easier because of the borrow checker.', '',
   '- Rust community'},
  {'Move toward a world where safe systems programming',
   'is the norm.', '', '- GolDDranks'},
  {'Hack without fear.', '', '- Aaron Turon, on Rust'},
  {'Rust: where the compiler is your pair programmer,',
   "and it's always right.", '', '- Rust folklore'},
}
